<a href="https://colab.research.google.com/github/Moe-phantom/Moe-phantom/blob/main/educational.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [8]:
class NumberDataset(Dataset):
  def __init__(self, data_range=(1,10)):
    self.numbers = list(range(data_range[0], data_range[1]))
  def __getitem__(self, index):
    number1 = float(self.numbers[index // len(self.numbers)])
    number2 = float(self.numbers[index % len(self.numbers)])
    return torch.tensor([number1,number2]), torch.tensor([number1+number2])
  def __len__(self):
    return len(self.numbers)**2
dataset = NumberDataset(data_range=(1,89))
for i in range(10):
  print(dataset[i])

(tensor([1., 1.]), tensor([2.]))
(tensor([1., 2.]), tensor([3.]))
(tensor([1., 3.]), tensor([4.]))
(tensor([1., 4.]), tensor([5.]))
(tensor([1., 5.]), tensor([6.]))
(tensor([1., 6.]), tensor([7.]))
(tensor([1., 7.]), tensor([8.]))
(tensor([1., 8.]), tensor([9.]))
(tensor([1., 9.]), tensor([10.]))
(tensor([ 1., 10.]), tensor([11.]))
